services:
  # api:
  #   build: .
  #   ports: 
  #     - "8080:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mydb;Username=postgres;Password=mysecretpassword
  #   depends_on:
  #     - db
  
  db:
    image: postgres:17
    restart: always
    # setting shared memory limit for docker compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data: 
    driver: local
